# -*- coding: utf-8 -*-
"""hierarchical clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lZ-nHrotTMMfJDr3-gr3_6BphKdn2V-p
"""



from google.colab import drive
drive.mount('/content/drive')

import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd

dataset = pd.read_csv('/content/drive/MyDrive/dataR2.csv')

x = dataset.iloc[:, [1, 2]].values

import scipy.cluster.hierarchy as shc  
dendro = shc.dendrogram(shc.linkage(x, method="ward"))  
mtp.title("Dendrogram Plot")  
mtp.ylabel("Euclidean Distances")  
mtp.xlabel("ca_cervix")  
mtp.show()

from sklearn.cluster import AgglomerativeClustering  
hc= AgglomerativeClustering(n_clusters=5, affinity='euclidean', linkage='ward')  
y_pred= hc.fit_predict(x)

mtp.scatter(x[y_pred == 0, 0], x[y_pred == 0, 1], s = 100, c = 'blue', label = 'Cluster 1')  
mtp.scatter(x[y_pred == 1, 0], x[y_pred == 1, 1], s = 100, c = 'green', label = 'Cluster 2')  
mtp.scatter(x[y_pred== 2, 0], x[y_pred == 2, 1], s = 100, c = 'red', label = 'Cluster 3')  
mtp.scatter(x[y_pred == 3, 0], x[y_pred == 3, 1], s = 100, c = 'cyan', label = 'Cluster 4')  
mtp.scatter(x[y_pred == 4, 0], x[y_pred == 4, 1], s = 100, c = 'magenta', label = 'Cluster 5')  
mtp.title('Clusters of customers')  
mtp.xlabel('behavior_sexualRisk (k$)')  
mtp.ylabel('behavior_eating (1-100)')  
mtp.legend()  
mtp.show()